-- AI Agent Platform — PostgreSQL schema（TASK-046 / 1.5.0，fresh PG 自举）
-- 与 schema_sqlite.sql 一一对应（22 张业务表）。全部 CREATE 带 IF NOT EXISTS，
-- 幂等可重复执行（同一库导入两次不报错）。
--
-- 为什么需要本文件（TASK-046 根因之一）：
--   1.4.0 的 _pg_init 只自举 settings / llm_endpoints 两张表，core 表
--   （users/permissions/roles/skills/agents/... 共 20 张）依赖"外部预置 schema"
--   （旧 pg-unified 手工建过）。但本次拍板策略引入"自建 agp-pg / 复用外部 PG"
--   路径——天然是 fresh PG，core 表不存在 → seed 的 INSERT INTO permissions 等
--   直接报错 → 启动失败。故在 _pg_init 里 executescript 本文件自举全量 schema，
--   使 PG 模式与 sqlite 模式能力对齐（clone/自建即可跑，零外部预置）。
--
-- 类型约定（与 sqlite 路径行为一致，业务代码零感知，D2）：
--   - id 主键统一 BIGINT GENERATED BY DEFAULT AS IDENTITY（对齐 IDENTITY_ID_TABLES
--     的 RETURNING id 语义）。
--   - 时间戳统一 TEXT，默认 to_char(now() AT TIME ZONE 'UTC','YYYY-MM-DD HH24:MI:SS')
--     （与 _to_pg 的 datetime('now') 翻译一致，双后端同一字符串格式）。
--   - JSON 列一律 TEXT（业务代码 json.loads/ json.dumps 按字符串处理，JSONB 会因
--     asyncpg 自动解码为 dict 破坏该契约）。唯一例外：mcp_servers.env 用 JSONB
--     DEFAULT '{}'::jsonb（与 1.4.0 _pg_init 的 ALTER 幂等补齐一致，API 层按 dict 读）。
--   - 浮点 REAL→DOUBLE PRECISION，布尔 INTEGER→BOOLEAN（mcp_servers.enabled）。
--   - 无 schema 前缀：依赖启动时设置的角色级默认 search_path=<agp>,public
--     （见 core.db._pg_bootstrap_schema），表自动落 agp schema。

-- ==================== 基础：RBAC / 用户 ====================
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS permissions (
  code TEXT PRIMARY KEY,
  description TEXT
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id BIGINT NOT NULL,
  permission_code TEXT NOT NULL,
  PRIMARY KEY (role_id, permission_code)
);

-- ==================== Agent / 对话 ====================
CREATE TABLE IF NOT EXISTS agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  system_prompt TEXT NOT NULL,
  model TEXT,
  temperature DOUBLE PRECISION DEFAULT 0.2,
  max_tokens INTEGER DEFAULT 1024,
  top_p DOUBLE PRECISION DEFAULT 0.9,
  backend TEXT NOT NULL DEFAULT 'custom',            -- TASK-037: custom | hermes
  hermes_profile TEXT,                               -- TASK-037: backend=hermes 时指向的 profile
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS agent_bindings (
  agent_id BIGINT NOT NULL,
  type TEXT NOT NULL,                                -- skill|mcp|plugin|rag|memory
  ref_id TEXT NOT NULL,
  PRIMARY KEY (agent_id, type, ref_id)
);

CREATE TABLE IF NOT EXISTS conversations (
  id TEXT PRIMARY KEY,
  agent_id BIGINT NOT NULL,
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conv_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT,
  ts TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS hitl_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task TEXT,
  reason TEXT,
  status TEXT DEFAULT 'pending',
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

-- ==================== 扩展工具：Skills / MCP / RAG ====================
CREATE TABLE IF NOT EXISTS skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  updated_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))  -- TASK-022 / F1
);

CREATE TABLE IF NOT EXISTS mcp_servers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  command TEXT NOT NULL,
  args TEXT DEFAULT '[]',                            -- JSON list（业务按字符串 json.loads）
  env JSONB DEFAULT '{}'::jsonb,                    -- TASK-022 / F1（API 层按 dict 读）
  enabled BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS rag_knowledge (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS rag_chunks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  knowledge_id BIGINT NOT NULL,
  seq INTEGER NOT NULL,
  text TEXT NOT NULL,
  embedding TEXT,                                    -- JSON list[float]（业务按字符串 json.loads）
  token_est INTEGER DEFAULT 0
);

-- ==================== 记忆（三层） ====================
CREATE TABLE IF NOT EXISTS memory_l0_raw (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT,
  ts TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  input TEXT,
  output TEXT
);

CREATE TABLE IF NOT EXISTS memory_l1_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_key TEXT NOT NULL,
  text TEXT NOT NULL,
  answer TEXT NOT NULL,
  embedding TEXT,                                    -- JSON list[float]
  ts TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS memory_l1_image (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  md5 TEXT UNIQUE NOT NULL,
  content_type TEXT,
  parsed TEXT,                                       -- JSON（业务按字符串 json.loads）
  ts TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS memory_l2_nodes (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  props TEXT DEFAULT '{}'                            -- JSON
);

CREATE TABLE IF NOT EXISTS memory_l2_edges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src TEXT NOT NULL,
  dst TEXT NOT NULL,
  type TEXT NOT NULL,
  props TEXT DEFAULT '{}',
  UNIQUE (src, dst, type)
);

CREATE TABLE IF NOT EXISTS memory_l2_buckets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  node_id TEXT NOT NULL,
  dim TEXT NOT NULL,                                 -- date|entity|process|topic
  key TEXT NOT NULL,
  record TEXT NOT NULL                               -- JSON
);

-- ==================== LLM endpoint / 系统配置 ====================
CREATE TABLE IF NOT EXISTS llm_endpoints (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  base_url TEXT NOT NULL,
  model TEXT NOT NULL,
  api_key TEXT NOT NULL DEFAULT '',
  timeout DOUBLE PRECISION NOT NULL DEFAULT 90,
  retries INTEGER NOT NULL DEFAULT 3,
  is_active INTEGER NOT NULL DEFAULT 0,
  created_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')),
  updated_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))
);
